name: Deploy to Cloud Run

env:
  SERVICE_NAME: finance-chatbot
  PROJECT_ID: utility-ridge-464606-a1
  DOCKER_IMAGE_URL: us-central1-docker.pkg.dev/utility-ridge-464606-a1/finace-chatbot-repo/finance-chatbot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE=${{ env.DOCKER_IMAGE_URL }}:${{ github.sha }}
          docker build -t $IMAGE -f Dockerfile .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image $IMAGE \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
